/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveCard: typeof import('./../components/ArchiveCard.vue')['default']
    Comment: typeof import('./../components/Comment.vue')['default']
    CommonFooter: typeof import('./../components/CommonFooter.vue')['default']
    ControlPanel: typeof import('./../components/ControlPanel.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    PostFooter: typeof import('./../components/PostFooter.vue')['default']
    PostHeader: typeof import('./../components/PostHeader.vue')['default']
    PostSearch: typeof import('./../components/PostSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar.vue')['default']
    Toc: typeof import('./../components/Toc.vue')['default']
  }
}
