/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    APlayer: typeof import('./../components/APlayer.vue')['default']
    ArchiveCard: typeof import('./../components/ArchiveCard.vue')['default']
    Comment: typeof import('./../components/Comment.vue')['default']
    CommonFooter: typeof import('./../components/CommonFooter.vue')['default']
    ControlPanel: typeof import('./../components/ControlPanel.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Hitokoto: typeof import('./../components/Hitokoto.vue')['default']
    'IAntDesign:githubFilled': typeof import('~icons/ant-design/github-filled')['default']
    'ICarbon:hazeNight': typeof import('~icons/carbon/haze-night')['default']
    'ICarbon:menu': typeof import('~icons/carbon/menu')['default']
    'ICarbon:rss': typeof import('~icons/carbon/rss')['default']
    'ICarbon:sun': typeof import('~icons/carbon/sun')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NRate: typeof import('naive-ui')['NRate']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NTag: typeof import('naive-ui')['NTag']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    PostFooter: typeof import('./../components/PostFooter.vue')['default']
    PostHeader: typeof import('./../components/PostHeader.vue')['default']
    PostSearch: typeof import('./../components/PostSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar.vue')['default']
    Toc: typeof import('./../components/Toc.vue')['default']
    Yiyan: typeof import('./../components/Yiyan.vue')['default']
  }
}
